spring:
  application:
    name: parser

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:

server:
  port: 9000

jsch:
  host:
  username:
  password:
  known_hosts: ~/.ssh/known_hosts

parser:
  save: false
  path: /root
  remote_dir_name: Port_All