spring:
  application:
    name: parser

  datasource:
    username: seoleir
    password: seoleir!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smtp

server:
  port: 9000

jsch:
  host: 82.148.5.235
  username: root
  password: d2EN1hwBkr1x
  known_hosts: ~/.ssh/known_hosts

parser:
  save: false
  path: /home/seoleir/
  remote_dir_name: Port_All